// css
import "./globals.css";
// fonts
import { Titillium_Web, Righteous, Caveat, Ubuntu, Ubuntu_Mono } from "next/font/google";
// components
import Logo from "@components/ui/logo";
import Button from "@components/ui/button";
import Tabs from "@components/ui/tabs";
import About from "@components/about";
import MyProfile from "@components/my-profile";
import Leaderboards from "@components/leaderboards";

const ubuntu = Ubuntu({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-ubuntu",
    weight: ["400", "500", "700"],
    preload: false,
});

const ubuntuMono = Ubuntu_Mono({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-ubuntuMono",
    weight: ["400", "700"],
    preload: false,
});

const caveat = Caveat({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-caveat",
    weight: ["400", "700"],
    preload: false,
});

const righteous = Righteous({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-righteous",
    weight: "400",
    preload: false,
});

const titilliumWeb = Titillium_Web({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-titilliumWeb",
    weight: ["400"],
    preload: false,
});

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            lang="en"
            className={`
                ${titilliumWeb.variable} 
                ${righteous.variable}
                ${caveat.variable}
                ${ubuntu.variable} 
                ${ubuntuMono.variable}
            `}
        >
            <body>
                <div className="flex items-center justify-between">
                    <Logo />
                    <Button className="">let's go!</Button>
                </div>
                <Tabs
                    components={[
                        ["My Profile", <MyProfile />],
                        ["Leaderboards", <Leaderboards />],
                        ["About", <About />],
                    ]}
                />
                {children}
            </body>
        </html>
    );
}
